# Webpage Entity
# A web page with URL, title, and content
#
# Extends document (which extends writing). Inherits:
#   From writing: content, author (→ person)
#   From document: title, url, published_at, fetched_at, data

id: webpage
plural: webpages
extends: document
name: Web Page
description: A web page with URL, title, and content

references:
  schema_org: https://schema.org/WebPage
  wikidata: Q36774  # web page

properties:
  # Webpage overrides url as required (the primary identifier)
  url:
    type: string
    format: url
    required: true
    description: The page URL

  snippet:
    type: string
    description: Short excerpt/description

  favicon:
    references: image
    description: Site favicon

  content_type:
    type: string
    description: MIME type of the content (e.g., text/html, application/json)

operations: [search, read]

display:
  primary: title
  secondary: url
  description: snippet
  icon: globe
  show_as_app: true
  app_name: Webpages

# Views for rendering webpage activities
views:
  search:
    title: Web Search
    tool_alias: search_web
    layout:
      - component: list
        data:
          source: activity
        item_component: search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          snippet: "{{snippet}}"
          favicon: "{{favicon}}"

  read:
    title: "{{activity.response.title}}"
    tool_alias: read_webpage
    layout:
      - component: content
        props:
          data: "{{activity.response.content}}"
          type: "{{activity.response.content_type}}"
          url: "{{activity.response.url}}"
