# Preview App
# Generic entity viewer — the fallback renderer.
# When no other app claims an entity type, preview renders it.
# Back/forward navigation shows the history of agent activity.

id: preview
name: Preview
icon: icon.svg
description: Generic entity viewer — renders any entity

views:
  detail:
    title: "{{params.title}}"
    toolbar:
      - component: url-bar
    layout:
      - component: entity-detail
        props:
          entity_type: "{{params.entity}}"
          entity_id: "{{params.id}}"
          data: "{{params.data}}"
