# Video Entity
# Video content from YouTube, Vimeo, or local files
#
# Extends media. Inherits:
#   From media: id, title, description, url, published_at, duration_ms, thumbnail
#
# Attribution: Uses `posts` relationship (account --posts--> video).
# The account is the observable source; the person behind it is linked
# via `claims`. This replaces the old `creator: references: person`.

id: video
plural: videos
extends: media
name: Video
description: Video content with metadata and optional transcript

references:
  schema_org: https://schema.org/VideoObject
  wikidata: Q34508  # video

properties:
  # Identity
  remote_id:
    type: string
    description: ID from the remote service (e.g., YouTube video ID "dQw4w9WgXcQ")

  # Content
  transcript:
    type: string
    description: Full transcript text (the key artifact for AI — plain text, no timestamps)

  transcript_segments:
    type: array
    description: Timestamped transcript segments for temporal navigation ("when do they talk about X?")
    items:
      start_ms:
        type: integer
        description: Segment start time in milliseconds
      end_ms:
        type: integer
        description: Segment end time in milliseconds
      text:
        type: string
        description: Text spoken during this segment

  chapters:
    type: array
    description: Chapter markers with timestamps
    items:
      title: string
      start_ms: integer

  # Technical (optional)
  resolution:
    type: string
    description: Video resolution (e.g., 1080p, 4K)

  codec:
    type: string
    description: Video codec (e.g., h264, vp9)

  # External sources (same video on different services)
  sources:
    type: array
    description: Where this video exists
    items:
      provider:
        type: string
        description: Service name (youtube, vimeo, local)
      id:
        type: string
        description: Provider-specific ID
      url:
        type: string
        format: url
        description: URL on that service

  # Engagement
  view_count:
    type: integer
    description: Number of views (if available from source)

  # Metadata
  fetched_at:
    type: datetime
    description: When we retrieved this data

operations: [get, search, list, transcript]

display:
  primary: title
  secondary: posted_by.display_name
  description: description
  image: thumbnail
  icon: play
  show_as_app: true

# Views for rendering video activities
# Note: Browser provides padding and status bar automatically
views:
  search:
    title: Videos
    layout:
      - component: list
        data:
          source: activity
        item_component: video-search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          thumbnail: "{{thumbnail}}"
          creator_name: "{{posted_by.display_name}}"
          creator_url: "{{posted_by.url}}"
          duration_ms: "{{duration_ms}}"
          view_count: "{{view_count}}"
          description: "{{description}}"

  search_recent:
    title: Recent Videos
    layout:
      - component: list
        data:
          source: activity
        item_component: video-search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          thumbnail: "{{thumbnail}}"
          creator_name: "{{posted_by.display_name}}"
          creator_url: "{{posted_by.url}}"
          duration_ms: "{{duration_ms}}"
          view_count: "{{view_count}}"
          description: "{{description}}"

  list:
    title: Channel Videos
    layout:
      - component: list
        data:
          source: activity
        item_component: video-search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          thumbnail: "{{thumbnail}}"
          creator_name: "{{posted_by.display_name}}"
          creator_url: "{{posted_by.url}}"
          duration_ms: "{{duration_ms}}"
          view_count: "{{view_count}}"
          description: "{{description}}"

  get:
    title: "{{activity.response.title}}"
    layout:
      - component: layout/stack
        props:
          direction: vertical
          gap: "12px"
          style:
            padding: "8px 12px"
        children:
          - component: video-header
            props:
              thumbnail: "{{activity.response.thumbnail}}"
              title: "{{activity.response.title}}"
              url: "{{activity.response.url}}"
              creator: "{{activity.response.posted_by.display_name}}"
              creatorUrl: "{{activity.response.posted_by.url}}"
              channel: "{{activity.response.posted_in.name}}"
              channelUrl: "{{activity.response.posted_in.url}}"
              subscribers: "{{activity.response.posted_in.member_count}}"
              duration: "{{activity.response.duration_ms}}"
              viewCount: "{{activity.response.view_count}}"
          - component: markdown
            props:
              content: "{{activity.response.description}}"

  transcript:
    title: "{{activity.response.title}}"
    layout:
      - component: layout/stack
        props:
          direction: vertical
          gap: "12px"
          style:
            padding: "8px 12px"
        children:
          - component: video-header
            props:
              thumbnail: "{{activity.response.thumbnail}}"
              title: "{{activity.response.title}}"
              url: "{{activity.response.url}}"
              creator: "{{activity.response.posted_by.display_name}}"
              creatorUrl: "{{activity.response.posted_by.url}}"
              channel: "{{activity.response.posted_in.name}}"
              channelUrl: "{{activity.response.posted_in.url}}"
              subscribers: "{{activity.response.posted_in.member_count}}"
              duration: "{{activity.response.duration_ms}}"
              label: "Transcript"
          - component: markdown
            props:
              content: "{{activity.response.transcript}}"
