# Videos App
# Entity-specific video player with channel byline, engagement stats, and actions.
# First community app — establishes patterns for all custom apps.

id: videos
name: Videos
description: Video player with channel info, actions, and metadata
icon: icon.svg
entities: ["video"]
default_view: generic-list

views:
  generic-list:
    title: Videos
    toolbar:
      - component: url-bar
      - component: action-bar
    layout:
      - component: entity-list
        props:
          entity: "{{entity}}"
          items: "{{entities}}"
          pending: "{{loading}}"
          error: "{{error}}"

  generic-detail:
    title: Video
    toolbar:
      - component: url-bar
      - component: action-bar
    layout:
      - component: video-detail
        props:
          entity: "{{entity}}"
          item: "{{entities}}"
          pending: "{{loading}}"
          error: "{{error}}"

  fallback:
    title: Response
    toolbar:
      - component: url-bar
      - component: action-bar
    layout:
      - component: request-response
        props:
          entity: "{{entity}}"
          response: "{{entities}}"
          pending: "{{loading}}"
          error: "{{error}}"
